# frozen_string_literal: true

require "rake/testtask"
require "rake/extensiontask"

task default: :test

Rake::ExtensionTask.new("rust_yaml") do |c|
  c.lib_dir = "lib/rust_yaml"
  c.ext_dir = "ext/rust_yaml"
end

task :dev do
  ENV['RB_SYS_CARGO_PROFILE'] = 'dev'
end

task :release do
  ENV['RB_SYS_CARGO_PROFILE'] = 'release'
end

Rake::TestTask.new do |t|
  t.deps << :dev << :compile
  t.test_files = FileList[File.expand_path("test/*_test.rb", __dir__)]
end

desc "Run benchmark comparing Rust YAML parser with Ruby's YAML parser"
task :benchmark => [:release, :compile] do
  ruby "bench/benchmark.rb"
end